### ISSUE TITLE
能否把输入参数改为音素

### ISSUE THREAD

**Issue by hyperzlib** [open-speech/speech-aligner#4]
如题，输入参数是拼音，但是这个软件好像只支持汉字，所以还得强行把拼音转成汉字。有办法直接输入拼音吗？

**Comment by megazone87** [comment]
可以，等我明天更新下( ¨̮ )

**Comment by megazone87** [comment]
现已更新，接收中文拼音（带调）输入，见[egs/cn_phn/data/text](https://github.com/open-speech/speech-aligner/blob/master/egs/cn_phn/data/text)
